# Generated by Django 6.0.3 on 2026-03-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_survey_description_alter_survey_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
