# Generated by Django 6.0.3 on 2026-03-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Texto libre'), ('checkbox', 'Opción múltiple')], default='text', max_length=20),
        ),
    ]
